# Vars
## Logo key, Mod1 is Alt. Mod4 is win key
set $mod Mod4
## Terminal emulator
set $term ghostty
set $menu qs -c noctalia-shell call launcher toggle
set $fm nemo
# Autostarts
## Noctalia Shell
exec qs -c noctalia-shell
# Binds
## Bring up the launcher
bindsym $mod+space exec $menu
## Spawn terminal
bindsym $mod+t exec $term
## Close focused window
bindsym $mod+q kill
## Basic Navigation
### focus window, vim style
bindsym $mod+h focus left
bindsym $mod+j focus down
bindsym $mod+k focus up
bindsym $mod+l focus right
### Move focused window, vim style
bindsym $mod+Shift+h move left
bindsym $mod+Shift+j move down
bindsym $mod+Shift+k move up
bindsym $mod+Shift+l move right
### Workspace shifting
bindsym $mod+1 workspace 1
bindsym $mod+2 workspace 2
bindsym $mod+3 workspace 3
bindsym $mod+4 workspace 4
bindsym $mod+5 workspace 5
bindsym $mod+6 workspace 6
bindsym $mod+7 workspace 7
bindsym $mod+8 workspace 8
bindsym $mod+9 workspace 9
### Move focused windows to specific workspaces
bindsym $mod+Shift+1 move container to workspace 1
bindsym $mod+Shift+2 move container to workspace 2
bindsym $mod+Shift+3 move container to workspace 3
bindsym $mod+Shift+4 move container to workspace 4
bindsym $mod+Shift+5 move container to workspace 5
bindsym $mod+Shift+6 move container to workspace 6
bindsym $mod+Shift+7 move container to workspace 7
bindsym $mod+Shift+8 move container to workspace 8
bindsym $mod+Shift+9 move container to workspace 9
### Switch between active workspaces
bindsym $mod+u workspace prev
bindsym $mod+i workspace next
## Make focused window fullscreen
bindsym $mod+f fullscreen
## Lock the screen
bindsym $mod+Alt+l qs -c noctalia-shell call lockscreen lock
## Browse wallpapers
bindsym $mod+y qs -c noctalia-shell call wallpaper toggle
## Open file manager
bindsym $mod+e $fm
## Reload Sway
bindsym $mod+Shift+c reload